Repository superedge/superedge, pull requests merged in 2021-07, with the labels that each got.

#183 add_community_meeting_info
  README.md
  README_CN.md
Labels: approved, kind/documentation, lgtm

#185 edgeadm: Deploy coredns for every edge node by servicegroup
  go.mod
  pkg/edgeadm/cmd/addon/edgeapps.go
  pkg/edgeadm/cmd/manifests.go
  pkg/edgeadm/common/common.go
  pkg/edgeadm/common/deploy_edge_coredns.go
  pkg/edgeadm/common/prepare_join_node.go
  pkg/edgeadm/constant/const.go
  pkg/edgeadm/constant/init.go
  pkg/edgeadm/constant/manifests/edge-coredns.go
  pkg/edgeadm/constant/manifests/tunnel-coredns.go
  pkg/edgeadm/steps/edge_app.go
  pkg/edgeadm/steps/join_master.go
  pkg/edgeadm/steps/lite_apiserver_init.go
  pkg/util/kubeadm/init.go
  pkg/util/kubeadm/join.go
Labels: approved, enhancement, lgtm, size/XL

#182 Update edge-node-ops_CN.md
  docs/components/edge-node-ops_CN.md
Labels: approved, documentation, kind/bug, lgtm, size/XS

#177 Separate the synchronization of podIP and Endpoints and set different synchronization cycles
  pkg/tunnel/proxy/modules/https/httpsmng/httpsserver.go
  pkg/tunnel/proxy/modules/stream/stream.go
  pkg/tunnel/proxy/modules/stream/streammng/connect/coredns.go
  pkg/tunnel/proxy/modules/stream/streammng/connect/coredns_test.go
  pkg/tunnel/util/const.go
Labels: approved, enhancement, kind/bug, lgtm

#187 tunnel-cloud adds metrics for HPA
  deployment/tunnel-cloud.yaml
  pkg/tunnel/conf/config.go
  pkg/tunnel/context/context_factory.go
  pkg/tunnel/context/nodecontext.go
  pkg/tunnel/metrics/metrics.go
  pkg/tunnel/proxy/modules/stream/stream.go
  pkg/tunnel/proxy/modules/stream/streammng/connect/grpcserver.go
  pkg/tunnel/util/const.go
Labels: approved, enhancement, lgtm, size/M

#188 Add technical articles related to SuprEdge
  README.md
  README_CN.md
  docs/installation/install_via_edgeadm.md
  docs/installation/install_via_edgeadm_CN.md
  docs/installation/tutorial_CN.md
  docs/tutorial.md
  docs/tutorial_CN.md
Labels: approved, kind/documentation, lgtm

#189 Node monitoring and support tunnel-cloud HPA based on the number of c…
  deployment/tunnel-cloud.yaml
  docs/components/hpa-monitor_CN.md
  docs/tutorial_CN.md
Labels: approved, enhancement, kind/documentation, lgtm

#186 edgeadm: add kube-vip as default HA component support.
  pkg/edgeadm/cmd/manifests.go
  pkg/edgeadm/cmd/model.go
  pkg/edgeadm/constant/const.go
  pkg/edgeadm/constant/manifests/kube-vip.go
  pkg/edgeadm/constant/options.go
  pkg/edgeadm/steps/edge_app.go
  pkg/edgeadm/steps/kube_vip.go
  pkg/util/kubeadm/init.go
  pkg/util/kubeadm/join.go
  pkg/util/kubeadm/reset.go
Labels: approved, enhancement, lgtm, size/L

#190 Use edgeadm to deploy a tunnel version that supports hpa and node mon…
  pkg/edgeadm/constant/manifests/tunnel-cloud.go
Labels: approved, enhancement, kind/feature, lgtm, size/XS

#191 0.5.0-bata.0 version released
  deployment/application-grid-controller.yaml
  deployment/application-grid-wrapper.yaml
  deployment/edge-health-admission.yaml
  deployment/edge-health.yaml
  deployment/lite-apiserver.yaml
  deployment/penetrator.yaml
  deployment/statefulset-grid-daemon.yaml
  deployment/tunnel-cloud.yaml
  deployment/tunnel-edge.yaml
  pkg/edgeadm/constant/manifests/application-grid-controller.go
  pkg/edgeadm/constant/manifests/application-grid-wrapper.go
  pkg/edgeadm/constant/manifests/edge-health-admission.go
  pkg/edgeadm/constant/manifests/edge-health.go
  pkg/edgeadm/constant/manifests/helper-job.go
  pkg/edgeadm/constant/manifests/lite-apiserver.go
  pkg/edgeadm/constant/manifests/tunnel-cloud.go
  pkg/edgeadm/constant/manifests/tunnel-edge.go
Labels: approved, lgtm, release-note

#192 Solve the deployment failure caused by tab
  README.md
  README_CN.md
  build/docker/penetrator-job/build.sh
  docs/installation/addon_superedge.md
  docs/installation/addon_superedge_CN.md
  docs/installation/install_edge_kubernetes.md
  docs/installation/install_edge_kubernetes_CN.md
  docs/tutorial_CN.md
  pkg/edgeadm/constant/manifests/tunnel-cloud.go
Labels: approved, kind/documentation, lgtm

#193 update tunnel-cloud HPA and deploy-monitor documentations
  docs/components/deploy-monitor_CN.md
  docs/components/tunnel-cloud-hpa_CN.md
  docs/tutorial_CN.md
Labels: kind/documentation, lgtm

#196 Update tunnel-cloud-hpa_CN.md
  docs/components/tunnel-cloud-hpa_CN.md
Labels: approved, enhancement, lgtm, size/S

#197 Solve problems with monitoring deployment
  docs/components/deploy-monitor_CN.md
Labels: approved, documentation, kind/bug, size/M

#200 Add the POD_NAME environment variable to the deployment of tunnel-cloud
  pkg/edgeadm/constant/manifests/tunnel-cloud.go
Labels: approved, kind/bug, lgtm, size/S

#199 Add proposal template
  docs/proposals/template.md
Labels: kind/documentation, lgtm

#201 Solve the problem of slow installation of prometheus-adapter using na…
  docs/components/tunnel-cloud-hpa_CN.md
Labels: enhancement

#198 Add related yaml files as resources for create prometheus-server, nod…
  deployment/prometheus-node-exporter.yaml
  deployment/prometheus-server.yaml
  deployment/tunel-cloud-hpa.yaml
  deployment/values.yaml
Labels: documentation, lgtm, size/L

#202 Replace the yaml file in the document with a link
  deployment/prometheus-server.yaml
  docs/components/deploy-monitor_CN.md
  docs/components/tunnel-cloud-hpa_CN.md
Labels: kind/documentation

#203 Release 0.5.0
  README.md
  README_CN.md
  build/docker/penetrator-job/build.sh
  deployment/application-grid-controller.yaml
  deployment/application-grid-wrapper.yaml
  deployment/edge-health-admission.yaml
  deployment/edge-health.yaml
  deployment/lite-apiserver.yaml
  deployment/penetrator.yaml
  deployment/statefulset-grid-daemon.yaml
  deployment/tunnel-cloud.yaml
  deployment/tunnel-edge.yaml
  docs/installation/addon_superedge.md
  docs/installation/addon_superedge_CN.md
  docs/installation/install_edge_kubernetes.md
  docs/installation/install_edge_kubernetes_CN.md
  docs/tutorial_CN.md
  pkg/edgeadm/constant/manifests/application-grid-controller.go
  pkg/edgeadm/constant/manifests/application-grid-wrapper.go
  pkg/edgeadm/constant/manifests/edge-health-admission.go
  pkg/edgeadm/constant/manifests/edge-health.go
  pkg/edgeadm/constant/manifests/helper-job.go
  pkg/edgeadm/constant/manifests/lite-apiserver.go
  pkg/edgeadm/constant/manifests/tunnel-cloud.go
  pkg/edgeadm/constant/manifests/tunnel-edge.go
Labels: kind/feature

#204 CHANGELOG-0.5
  CHANGELOG/CHANGELOG-0.5.md
  CHANGELOG/README.md
Labels: approved

#206 Update install_edge_kubernetes.md and install_edge_kubernetes_CN.md
  docs/installation/install_edge_kubernetes.md
  docs/installation/install_edge_kubernetes_CN.md
Labels: approved, documentation, lgtm, size/M
