Repository superedge/superedge, pull requests merged in 2021-06, with the labels that each got.

#134 Supredge: add Travis CI configuration to the supredge project
  .travis.yml
  build/lib/golang.mk
Labels: kind/test, lgtm

#129 edgeadm: Add install add-on edge apps in TKE cluster feature.
  pkg/edgeadm/cmd/addon/addon.go
  pkg/edgeadm/cmd/addon/edgeapps.go
  pkg/edgeadm/common/common.go
  pkg/edgeadm/common/deploy_edge_preflight.go
  pkg/edgeadm/common/deploy_service_group.go
  pkg/edgeadm/common/deploy_tunnel.go
  pkg/edgeadm/common/update_config.go
  pkg/edgeadm/constant/const.go
  pkg/edgeadm/constant/manifests/edge-preflight.go
  pkg/util/kubeadm/token.go
  pkg/util/kubeclient/client.go
Labels: approved, enhancement, lgtm

#132 edgeadm: disable selinux, enable kubelet service, enable lite-apiserv…
  pkg/edgeadm/constant/const.go
  pkg/edgeadm/constant/init_node.go
  pkg/edgeadm/steps/init_node.go
Labels: approved, kind/bug, lgtm

#138 fetch the NewInitNodePhase() function directly into an init-node.sh script
  pkg/edgeadm/constant/init.go
  pkg/edgeadm/constant/init_node.go
  pkg/edgeadm/steps/init-node.sh
  pkg/edgeadm/steps/init_node.go
Labels: approved, lgtm

#139 ServiceGroup for multi cluster
  cmd/application-grid-controller/app/server.go
  pkg/application-grid-controller/config/config.go
  pkg/application-grid-controller/controller/common/labels.go
  pkg/application-grid-controller/controller/common/vars.go
  pkg/application-grid-controller/controller/deployment/controller.go
  pkg/application-grid-controller/controller/deployment/fed_deployment.go
  pkg/application-grid-controller/controller/deployment/namespace.go
  pkg/application-grid-controller/controller/deployment/sync.go
  pkg/application-grid-controller/controller/deployment/util/deployment_util.go
  pkg/application-grid-controller/controller/service/controller.go
  pkg/application-grid-controller/controller/service/fed_service.go
  pkg/application-grid-controller/controller/service/namespace.go
  pkg/application-grid-controller/controller/service/sync.go
  pkg/application-grid-controller/controller/service/util/service_util.go
  pkg/application-grid-controller/util/kubeconfig.go
  pkg/application-grid-controller/util/status_compare.go
Labels: enhancement, size/XXL

#141 BugFix: Add edge-health deploy
  docs/installation/install_edge_kubernetes.md
  docs/installation/install_edge_kubernetes_CN.md
  pkg/edgeadm/common/deploy_edge_health.go
  pkg/edgeadm/constant/init.go
  pkg/edgeadm/constant/manifests/tunnel-cloud.go
Labels: approved, kind/bug, lgtm, size/S

#142 Modify the download link of penetrator deployment yaml
  docs/components/edge-node-ops_CN.md
  docs/installation/addnode_via_penetrator_CN.md
Labels: documentation

#145 Version: Update release the v0.4.0.beta.0 version into v0.4.0-beta.0 …
  README.md
  README_CN.md
  deployment/application-grid-controller.yaml
  deployment/application-grid-wrapper.yaml
  deployment/edge-health-admission.yaml
  deployment/edge-health.yaml
  deployment/lite-apiserver.yaml
  deployment/statefulset-grid-daemon.yaml
  deployment/tunnel-cloud.yaml
  deployment/tunnel-edge.yaml
  docs/installation/install_edge_kubernetes.md
  docs/installation/install_edge_kubernetes_CN.md
  pkg/edgeadm/constant/manifests/application-grid-controller.go
  pkg/edgeadm/constant/manifests/application-grid-wrapper.go
  pkg/edgeadm/constant/manifests/edge-health-admission.go
  pkg/edgeadm/constant/manifests/edge-health.go
  pkg/edgeadm/constant/manifests/helper-job.go
  pkg/edgeadm/constant/manifests/lite-apiserver.go
  pkg/edgeadm/constant/manifests/tunnel-cloud.go
  pkg/edgeadm/constant/manifests/tunnel-edge.go
Labels: approved, lgtm, release-note

#149 add secrets and namespaces clusterrole for grid controller
  deployment/application-grid-controller.yaml
Labels: approved, lgtm, size/S

#150 docs: add hostname requirements to deployment docs
  docs/installation/install_edge_kubernetes.md
  docs/installation/install_edge_kubernetes_CN.md
Labels: approved, lgtm

#151 edgeadm: update get tunnel-cloud service NodePort
  pkg/edgeadm/common/deploy_tunnel.go
  pkg/edgeadm/constant/const.go
Labels: approved, lgtm, release-note

#152 edgeadm: Add application-grid-controller ClusterRole secrets and namespace
  pkg/edgeadm/constant/manifests/application-grid-controller.go
Labels: kind/bug, size/S

#153 Add the command to get the nodePort for SSH login in the document
  docs/components/edge-node-ops_CN.md
Labels: approved, documentation, kind/documentation, lgtm

#154 multicluster serviceGroup doc
  docs/components/serviceGroup.md
  docs/components/serviceGroup_CN.md
Labels: documentation, size/M

#157 Migrate the mirror of the penetrator to tcr
  deployment/penetrator.yaml
Labels: approved, documentation, enhancement, lgtm

#158 docs: Add addon_superedge_CN.md and addon_superedge_CN.md files about addon SuperEdge to native Kuberntes clusters
  docs/installation/addon_superedge.md
  docs/installation/addon_superedge_CN.md
Labels: documentation, size/L

#159 Delete useless files of tunnel components
  pkg/tunnel/proxy/tcp/tcpmng/tcpmng.go
  pkg/tunnel/proxy/tcp/tcpmsg/tcpprotocol.go
Labels: approved, kind/cleanup, lgtm, size/S

#156 fix err in serviceGroup doc
  docs/components/serviceGroup.md
Labels: documentation, size/S

#161 Add the English documentation of the penetrator
  docs/installation/addnode_via_penetartor.md
  docs/installation/addnode_via_penetrator_CN.md
Labels: approved, documentation, lgtm, size/L

#162 Add English documentation of tunnel ssh module
  docs/components/edge-node-ops.md
  docs/components/edge-node-ops_CN.md
Labels: approved, documentation, lgtm, size/L

#164 edgeadm: Update init-node.sh about ubuntu ufw
  pkg/edgeadm/steps/init-node.sh
Labels: approved, kind/bug, lgtm, size/S

#163 Add CHANGELOG-0.4.md
  CHANGELOG/CHANGELOG-0.4.md
  CHANGELOG/README.md
Labels: approved, documentation, kind/documentation, lgtm, size/S

#165 edgeadm: get master ip from cluster-info when print join command
  pkg/edgeadm/cmd/addon/edgeapps.go
  pkg/edgeadm/common/update_config.go
  pkg/util/kubeadm/token.go
Labels: approved, enhancement, lgtm, size/S

#166 update parent secret namespaces
  cmd/application-grid-controller/app/server.go
  pkg/application-grid-controller/controller/common/vars.go
Labels: approved, kind/cleanup, lgtm, size/S

#167 Avoid using yaml to delete all resources under edge-system when deleting
  deployment/penetrator.yaml
Labels: approved, kind/bug, lgtm, size/XS

#168 Updated Roadmap
  docs/roadmap.md
Labels: approved, kind/documentation, lgtm, size/S

#174 edgeadm: Fix x509 certificate bug when joining edge nodes
  pkg/edgeadm/constant/const.go
  pkg/edgeadm/steps/lite_apiserver_clean.go
  pkg/edgeadm/steps/lite_apiserver_init.go
  pkg/util/tools.go
Labels: approved, kind/bug, lgtm, size/L

#175 docs addon_superedge_CN.md change penetrator spelling mistake
  docs/installation/addnode_via_penetrator.md
Labels: approved, kind/bug, lgtm, size/S

#176 edgeadm: Fix join master kube-apiservice add tunnel-coredns addr
  pkg/edgeadm/common/deploy_lite_apiserver.go
  pkg/edgeadm/constant/const.go
  pkg/edgeadm/steps/join_master.go
  pkg/util/kubeadm/join.go
Labels: kind/bug, size/L
