Repository superedge/superedge, pull requests merged in 2021-12, with the labels that each got.

#295 add log tips when the cache type is not supported
  pkg/lite-apiserver/storage/storage.go
Labels: enhancement, approved, lgtm, size/S

#296 add pprof trace and symbol debugging
  pkg/lite-apiserver/server/server.go
Labels: approved, lgtm, size/XS

#306 Add setnode function
  pkg/site-manager/controller/unit.go
  pkg/site-manager/utils/node.go
Labels: enhancement, approved, lgtm, size/L
