Repository superedge/superedge, pull requests merged in 2021-11, with the labels that each got.

#272 lite-apiserver support pprof debugging
  pkg/lite-apiserver/server/server.go
Labels: kind/feature, approved, lgtm, size/XS

#261 Fix examples/Tars/testapp import "testapp" error
  examples/Tars/testapp/httpserver/Handler.go
  examples/Tars/testapp/httpserver/main.go
  examples/Tars/testapp/httpserver/makefile
  examples/Tars/testapp/testapp/Hello.go
  examples/Tars/testapp/testapp/Hello.tars.go
  examples/Tars/testapp/testserver/Imp.go
  examples/Tars/testapp/testserver/main.go
  examples/Tars/testapp/testserver/makefile
Labels: kind/feature, approved, lgtm, size/XL

#273 go.sum: FIX github.com/google/flatbuffers pkg question
  go.mod
  go.sum
Labels: kind/bug, size/L

#278 Modified Slack link to CNCF workspace
  README.md
Labels: kind/documentation

#280 docs: Update GOVERNANCE files
  GOVERNANCE.md
Labels: size/S

#282 edgeadm: support proxy edge nodes and non-edge nodes through patch ku…
  pkg/edgeadm/cmd/change/kubeadm.go
  pkg/edgeadm/cmd/revert/kubeadm.go
  pkg/edgeadm/common/update_config.go
  pkg/edgeadm/constant/const.go
  pkg/edgeadm/constant/init.go
Labels: enhancement, approved, size/L

#288 Add CloudNodelLabel function
  pkg/edgeadm/constant/const.go
  pkg/edgeadm/steps/lite_apiserver_init.go
  pkg/util/kubeadm/join.go
Labels: enhancement, approved, size/L

#289 Add sites manager to nodeunit and nodegroup
  build/docker/site-manager/Dockerfile
  cmd/site-manager/app/options/options.go
  cmd/site-manager/app/server.go
  cmd/site-manager/site-manager.go
  deployment/site-manager.yaml
  docs/components/site-manager_CN.md
  go.mod
  go.sum
  pkg/edgeadm/constant/const.go
  pkg/site-manager-test.sh
  pkg/site-manager/apis/site/v1/doc.go
  pkg/site-manager/apis/site/v1/groupversion_info.go
  pkg/site-manager/apis/site/v1/nodegroup_types.go
  pkg/site-manager/apis/site/v1/nodeunit_types.go
  pkg/site-manager/apis/site/v1/register.go
  pkg/site-manager/apis/site/v1/zz_generated.deepcopy.go
  pkg/site-manager/constant/const.go
  pkg/site-manager/controller/controller.go
  pkg/site-manager/controller/node.go
  pkg/site-manager/controller/node_group.go
  pkg/site-manager/controller/unit.go
  pkg/site-manager/crd/demo/nodegroup_demo.yaml
  pkg/site-manager/crd/demo/nodeunit_demo.yaml
  pkg/site-manager/crd/site.superedge.io_nodegroups.yaml
  pkg/site-manager/crd/site.superedge.io_nodeunits.yaml
  pkg/site-manager/generated/clientset/versioned/clientset.go
  pkg/site-manager/generated/clientset/versioned/doc.go
  pkg/site-manager/generated/clientset/versioned/fake/clientset_generated.go
  pkg/site-manager/generated/clientset/versioned/fake/doc.go
  pkg/site-manager/generated/clientset/versioned/fake/register.go
  pkg/site-manager/generated/clientset/versioned/scheme/doc.go
  pkg/site-manager/generated/clientset/versioned/scheme/register.go
  pkg/site-manager/generated/clientset/versioned/typed/site/v1/doc.go
  pkg/site-manager/generated/clientset/versioned/typed/site/v1/fake/doc.go
  pkg/site-manager/generated/clientset/versioned/typed/site/v1/fake/fake_nodegroup.go
  pkg/site-manager/generated/clientset/versioned/typed/site/v1/fake/fake_nodeunit.go
  pkg/site-manager/generated/clientset/versioned/typed/site/v1/fake/fake_site_client.go
  pkg/site-manager/generated/clientset/versioned/typed/site/v1/generated_expansion.go
  pkg/site-manager/generated/clientset/versioned/typed/site/v1/nodegroup.go
  pkg/site-manager/generated/clientset/versioned/typed/site/v1/nodeunit.go
  pkg/site-manager/generated/clientset/versioned/typed/site/v1/site_client.go
  pkg/site-manager/generated/informers/externalversions/factory.go
  pkg/site-manager/generated/informers/externalversions/generic.go
  pkg/site-manager/generated/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/site-manager/generated/informers/externalversions/site/interface.go
  pkg/site-manager/generated/informers/externalversions/site/v1/interface.go
  pkg/site-manager/generated/informers/externalversions/site/v1/nodegroup.go
  pkg/site-manager/generated/informers/externalversions/site/v1/nodeunit.go
  pkg/site-manager/generated/listers/site/v1/expansion_generated.go
  pkg/site-manager/generated/listers/site/v1/nodegroup.go
  pkg/site-manager/generated/listers/site/v1/nodeunit.go
  pkg/site-manager/utils/common.go
  pkg/site-manager/utils/node.go
  pkg/site-manager/utils/node_group.go
  pkg/site-manager/utils/unit.go
  pkg/util/kubeclient/client.go
  pkg/util/output.go
  pkg/util/tools.go
Labels: enhancement, size/XXL

#292 fix rand.Rand use in lite-apiserver storage
  pkg/lite-apiserver/storage/file_storage.go
Labels: approved, lgtm, size/XS

#291 doc(feat): use gpu in superedge
  examples/gpu/SuperEdge_GPU_CN.md
Labels: documentation, approved, lgtm, size/L
