Repository superedge/superedge, pull requests merged in 2021-05, with the labels that each got.

#96 fix serviceGroup link in readme
  README.md
  README_CN.md
Labels: documentation

#115 edegadm: FIX the unsuccessful loading of ip_vs degenerates into iptables
  pkg/edgeadm/common/static_pkg.go
  pkg/edgeadm/constant/init_node.go
  pkg/edgeadm/steps/init_node.go
  pkg/util/runcmd.go
Labels: approved, kind/bug, lgtm

#116 edgeadm: FIX tunnel-edge uses public network address to link tunnel-cloud
  pkg/edgeadm/common/common.go
  pkg/edgeadm/common/deploy_tunnel.go
  pkg/edgeadm/steps/edge_app.go
Labels: approved, kind/bug, lgtm

#122 add CHANGELOG-0.3.md
  CHANGELOG/CHANGELOG-0.3.md
  CHANGELOG/README.md
Labels: approved, lgtm

#110 edgeadm: Add edgeadm add-on apps deletion feature
  cmd/edgeadm/app/server.go
  pkg/edgeadm/cmd/addon/addon.go
  pkg/edgeadm/cmd/addon/edgeapps.go
  pkg/edgeadm/common/common.go
  pkg/edgeadm/common/deploy_edge_health.go
  pkg/edgeadm/common/deploy_lite_apiserver.go
  pkg/edgeadm/common/deploy_service_group.go
  pkg/edgeadm/common/deploy_tunnel.go
  pkg/edgeadm/common/update_config.go
  pkg/edgeadm/constant/const.go
  pkg/edgeadm/steps/edge_app.go
Labels: approved, enhancement

#123 Add changelog 0.3
  CHANGELOG/CHANGELOG-0.3.md
Labels: documentation

#126 lite-apiserver: add modify-request-accept param
  go.sum
  pkg/lite-apiserver/config/config.go
  pkg/lite-apiserver/options/server_options.go
  pkg/lite-apiserver/proxy/handler.go
  pkg/lite-apiserver/proxy/proxy.go
Labels: enhancement

#125 check node name parameter, the IPv4 format is not supported
  pkg/util/kubeadm/init.go
  pkg/util/kubeadm/join.go
Labels: enhancement

#119 Change default installed namespace to 'edge-system'
  deployment/application-grid-controller.yaml
  deployment/application-grid-wrapper.yaml
  deployment/edge-health-admission.yaml
  deployment/edge-health-webhook.yaml
  deployment/edge-health.yaml
  deployment/lite-apiserver.yaml
  deployment/statefulset-grid-daemon.yaml
  deployment/tunnel-cloud.yaml
  deployment/tunnel-coredns.yaml
  deployment/tunnel-edge.yaml
  docs/components/edge-health.md
  docs/components/edge-health_CN.md
  docs/components/tunnel.md
  docs/components/tunnel_CN.md
  docs/installation/install_manually.md
  docs/installation/install_manually_CN.md
  pkg/edge-health/check/check.go
  pkg/edge-health/util/util.go
  pkg/edgeadm/cmd/change/kubeadm.go
  pkg/edgeadm/cmd/manifests.go
  pkg/edgeadm/cmd/revert/kubeadm.go
  pkg/edgeadm/common/common.go
  pkg/edgeadm/common/deploy_edge_health.go
  pkg/edgeadm/common/deploy_lite_apiserver.go
  pkg/edgeadm/common/deploy_service_group.go
  pkg/edgeadm/common/deploy_tunnel.go
  pkg/edgeadm/common/update_config.go
  pkg/edgeadm/constant/const.go
  pkg/edgeadm/constant/manifests/application-grid-controller.go
  pkg/edgeadm/constant/manifests/application-grid-wrapper.go
  pkg/edgeadm/constant/manifests/edge-health-admission.go
  pkg/edgeadm/constant/manifests/edge-health-webhook-configurations.go
  pkg/edgeadm/constant/manifests/edge-health.go
  pkg/edgeadm/constant/manifests/flannel.go
  pkg/edgeadm/constant/manifests/helper-job.go
  pkg/edgeadm/constant/manifests/lite-apiserver.go
  pkg/edgeadm/constant/manifests/tunnel-cloud.go
  pkg/edgeadm/constant/manifests/tunnel-coredns.go
  pkg/edgeadm/constant/manifests/tunnel-edge.go
  pkg/edgeadm/steps/cni_addon.go
  pkg/edgeadm/steps/edge_app.go
  pkg/helper-job/deploy/change.go
Labels: enhancement
