Repository superedge/superedge, pull requests merged in 2021-09, with the labels that each got.

#229 Addon edgexfoundry to edge cluster
  go.mod
  go.sum
  pkg/edgeadm/cmd/addon/addon.go
  pkg/edgeadm/cmd/addon/edgex.go
  pkg/edgeadm/common/common.go
  pkg/edgeadm/constant/const.go
  pkg/edgeadm/constant/manifests/edgex/edgex-application-server.go
  pkg/edgeadm/constant/manifests/edgex/edgex-configmap.go
  pkg/edgeadm/constant/manifests/edgex/edgex-core-server.go
  pkg/edgeadm/constant/manifests/edgex/edgex-device-random.go
  pkg/edgeadm/constant/manifests/edgex/edgex-device-server.go
  pkg/edgeadm/constant/manifests/edgex/edgex-k8s.go
  pkg/edgeadm/constant/manifests/edgex/edgex-mqtt.go
  pkg/edgeadm/constant/manifests/edgex/edgex-support-server.go
  pkg/edgeadm/constant/manifests/edgex/edgex-sys-mgmt-agent.go
  pkg/edgeadm/constant/manifests/edgex/edgex-ui.go
  pkg/util/kubeclient/delete.go
Labels: documentation, approved, lgtm, size/XXL

#232 Add prometheus-proxy yaml
  deployment/prometheus-proxy.yaml
  deployment/prometheus-server.yaml
  deployment/tunnel-cloud.yaml
Labels: kind/feature, lgtm

#238 Edgex: Add test edgex deploy file edgex-app-service-configurable.yaml…
  deployment/edgex/edgex-app-service-configurable.yaml
  deployment/edgex/edgex-device-random.yaml
Labels: enhancement, size/L

#234 Document for installing and using edgexfoundry
  docs/img/edgex-command.png
  docs/img/edgex-consul.png
  docs/img/edgex-data.png
  docs/img/edgex-get.png
  docs/img/edgex-hivemq-connect.png
  docs/img/edgex-hivemq-create.png
  docs/img/edgex-hivemq-message.png
  docs/img/edgex-layer.png
  docs/img/edgex-ui.png
  docs/img/superdge_addon_edgex.png
  docs/img/superedge_edgex_edge_edge.png
  docs/installation/addon_edgex_CN.md
Labels: documentation, do-not-merge/work-in-progress

#243 Add examples/Tars
  examples/Tars/README.md
  examples/Tars/images/1.png
  examples/Tars/images/2.png
  examples/Tars/tarscli-env/start.sh
  examples/Tars/tarscli-env/tarscli-env.md
  examples/Tars/testapp/httpserver/Dockerfile
  examples/Tars/testapp/httpserver/Handler.go
  examples/Tars/testapp/httpserver/Hello.tars
  examples/Tars/testapp/httpserver/Html.tmpl
  examples/Tars/testapp/httpserver/_server_meta.yaml
  examples/Tars/testapp/httpserver/main.go
  examples/Tars/testapp/httpserver/makefile
  examples/Tars/testapp/httpserver/start.sh
  examples/Tars/testapp/testserver/Dockerfile
  examples/Tars/testapp/testserver/Hello.tars
  examples/Tars/testapp/testserver/Imp.go
  examples/Tars/testapp/testserver/_server_meta.yaml
  examples/Tars/testapp/testserver/main.go
  examples/Tars/testapp/testserver/makefile
  examples/Tars/testapp/testserver/start.sh
  examples/Tars/yaml/baseserver/init_db/db_cache_web.sql
  examples/Tars/yaml/baseserver/init_db/db_tars.sql
  examples/Tars/yaml/baseserver/init_db/db_tars_web.sql
  examples/Tars/yaml/baseserver/init_db/db_user_system.sql
  examples/Tars/yaml/baseserver/init_db/init.sh
  examples/Tars/yaml/baseserver/tars-configmap.yaml
  examples/Tars/yaml/baseserver/tarsdb.yaml
  examples/Tars/yaml/baseserver/tarsnotify.yaml
  examples/Tars/yaml/baseserver/tarsregistry.yaml
  examples/Tars/yaml/baseserver/tarsweb.yaml
  examples/Tars/yaml/example/httpserver.yaml
  examples/Tars/yaml/example/tarsserver-config.yaml
  examples/Tars/yaml/example/testserver.yaml
  examples/Tengine/README.md
  examples/Tengine/SuperEdge_Tengine_User_Manual.md
  examples/Tengine/SuperEdge_Tengine_User_Manual_CN.md
Labels: enhancement, approved, lgtm, size/XXL

#244 docs: Add MAINTAINERS file
  MAINTAINERS.md
Labels: documentation, approved, size/M

#250 docs: Add Troubleshooting and Feedback
  README.md
  README_CN.md
  SECURITY.md
Labels: documentation, size/S

#252 Use multiple pipes to read an io.ReaderClose at the same time
  pkg/lite-apiserver/proxy/proxy.go
  pkg/lite-apiserver/proxy/util.go
Labels: enhancement

#258 MAINTAINERS: Update MAINTAINERS list and Outstanding CONTRIIBUTOR
  CONTRIIBUTOR.md
  MAINTAINERS.md
Labels: documentation, approved, size/S
