Repository superedge/superedge, pull requests merged in 2021-08, with the labels that each got.

#210 remove files from examples dir
  examples/README.md
Labels: approved, documentation, kind/cleanup, kind/documentation, lgtm

#212 Add empty readme
  examples/README.md
Labels: approved, kind/documentation, lgtm

#214 Add an article comparing tunnel and anp
  docs/tutorial_CN.md
Labels: kind/documentation, approved, lgtm

#215 add SuperEdge_Tengine_User_Manual
  examples/SuperEdge_Tengine_User_Manual.md
  examples/SuperEdge_Tengine_User_Manual_CN.md
Labels: kind/documentation, approved, lgtm

#216 docs: add network bandwidth tips
  docs/installation/install_edge_kubernetes.md
  docs/installation/install_edge_kubernetes_CN.md
Labels: kind/documentation, approved, lgtm

#220 Manually deploy the tunnel-cloud certificate and the domain name is incorrectly signed
  docs/installation/install_manually.md
  docs/installation/install_manually_CN.md
Labels: documentation, approved, lgtm
