Repository superedge/superedge, pull requests merged in 2022-05, with the labels that each got.

#379 Solve the problem of tunnel http-proxy server processing concurrent r…
  pkg/tunnel/proxy/modules/http-proxy/http_proxy.go
Labels: kind/bug

#381 Modfiy ServiceGroup_CN.md to explain ServiceGroup
  docs/components/serviceGroup_CN.md
  docs/img/demo_deploymentgrid_internal.jpg
  docs/img/demo_headless_enable.jpg
  docs/img/demo_node_label.jpg
  docs/img/demo_node_list.jpg
  docs/img/demo_nodegroup_list.jpg
  docs/img/demo_nodeunit_list.jpg
  docs/img/demo_statefulsetgrid_internal.jpg
  docs/img/demo_stsgrid_headless.jpg
Labels: documentation

#382 Add parameters to skip the verification of the domain name and ip sig…
  pkg/lite-apiserver/config/config.go
  pkg/lite-apiserver/options/server_options.go
  pkg/lite-apiserver/transport/transport_mgr.go
Labels: kind/feature

#388 tunnel supports ExternalName service forwarding
  pkg/tunnel/conf/config.go
  pkg/tunnel/proxy/common/indexers/indexCache.go
  pkg/tunnel/proxy/common/proxy.go
  pkg/tunnel/proxy/handlers/http-proxy_handler.go
  pkg/tunnel/proxy/modules/egress/connect/egress_server.go
  pkg/tunnel/proxy/modules/http-proxy/connect/cloud_server.go
  pkg/tunnel/proxy/modules/http-proxy/http_proxy.go
  pkg/tunnel/util/const.go
  pkg/tunnel/util/util.go
Labels: kind/feature

#391 skip ca verification for serviceaccount
  pkg/lite-apiserver/transport/transport_mgr.go
Labels: kind/bug
