Repository superedge/superedge, pull requests merged in 2022-02, with the labels that each got.

#324 add go fmt check on github actions
  .github/workflows/verify.yaml
  cmd/application-grid-controller/app/server.go
  cmd/edge-health/app/server.go
  hack/verify-gofmt.sh
  pkg/application-grid-controller/apis/superedge.io/v1/zz_generated.deepcopy.go
  pkg/edge-health/check/check.go
  pkg/edge-health/checkplugin/kubeletauthcheck.go
  pkg/edge-health/checkplugin/pingcheck.go
  pkg/edgeadm/cmd/addon/edgex.go
  pkg/edgeadm/cmd/change/kubeadm.go
  pkg/edgeadm/cmd/revert/kubeadm.go
  pkg/edgeadm/common/update_config.go
  pkg/edgeadm/constant/const.go
  pkg/penetrator/apis/nodetask.apps.superedge.io/v1beta1/zz_generated.deepcopy.go
  pkg/site-manager/apis/site/v1/zz_generated.deepcopy.go
  pkg/tunnel/token/tokencache.go
Labels: documentation, approved, lgtm, kind/test, size/L

#337 Offline package url in COS forwards compatibility
  README.md
  README_CN.md
  docs/installation/install_edge_kubernetes.md
  docs/installation/install_edge_kubernetes_CN.md
  examples/wasmedge/wasmedge.md
Labels: enhancement, approved, size/S

#336 use constant instead the string
  pkg/lite-apiserver/constant/constant.go
  pkg/lite-apiserver/proxy/proxy.go
Labels: approved, lgtm, size/XS

#263 feat[lite-apiserver]: add network interface flag for multi nic on edg…
  pkg/lite-apiserver/config/config.go
  pkg/lite-apiserver/options/server_options.go
  pkg/lite-apiserver/transport/transport.go
  pkg/lite-apiserver/transport/transport_mgr.go
  pkg/util/tools.go
Labels: enhancement, approved, lgtm, size/L

#341 #340 support use pebble as storage
  go.mod
  go.sum
  pkg/lite-apiserver/config/config.go
  pkg/lite-apiserver/constant/constant.go
  pkg/lite-apiserver/storage/pebble_storage.go
  pkg/lite-apiserver/storage/pebble_storage_test.go
  pkg/lite-apiserver/storage/storage.go
Labels: duplicate, approved, lgtm, size/L

#85 Use the TCP forwarding function of the tunnel to achieve access to th…
  examples/README.md
  examples/access-edge-service/README.md
  examples/access-edge-service/img/tcp-forward.png
  examples/access-edge-service/yaml/tcp/edge-service.yaml
  examples/access-edge-service/yaml/tcp/tunnel-cloud.yaml
  examples/access-edge-service/yaml/tcp/tunnel-edge.yaml
Labels: documentation
