Repository superedge/superedge, pull requests merged in 2022-04, with the labels that each got.

#370 edgeadm: Support tkesatck addon superedge edge apps to tke cluster
  build/lib/golang.mk
  go.mod
  go.sum
  pkg/edgeadm/cmd/change/kubeadm.go
  pkg/edgeadm/common/common.go
  pkg/edgeadm/common/deploy_edge_preflight.go
  pkg/edgeadm/common/deploy_tunnel.go
  pkg/edgeadm/common/prepare_join_node.go
  pkg/edgeadm/common/update_config.go
  pkg/edgeadm/constant/const.go
  pkg/edgeadm/steps/join_master.go
  pkg/util/kubeadm/join.go
Labels: enhancement

#371 application-grid-controller and application-grid-wrapper support k8s 1.22
  build/docker/application-grid-controller/Dockerfile
  build/docker/application-grid-controller/build.sh
  go.mod
  go.sum
  pkg/application-grid-controller/controller/common/deploymentgrid-crd.go
  pkg/application-grid-controller/controller/common/servicegrid-crd.go
  pkg/application-grid-controller/controller/common/statefulsetgrid-crd.go
  pkg/application-grid-controller/manifests/superedge.io_deploymentgrids.yaml
  pkg/application-grid-controller/manifests/superedge.io_servicegrids.yaml
  pkg/application-grid-controller/manifests/superedge.io_statefulsetgrids.yaml
  pkg/application-grid-controller/prepare/crd.go
  pkg/application-grid-controller/prepare/crd_test.go
  pkg/application-grid-wrapper/server/handler.go
  pkg/application-grid-wrapper/server/server.go
  pkg/application-grid-wrapper/storage/cache.go
  pkg/application-grid-wrapper/storage/cache_test.go
  pkg/application-grid-wrapper/storage/endpointslicev1_handler.go
  pkg/application-grid-wrapper/storage/endpointslicev1beta1_handler.go
  pkg/application-grid-wrapper/storage/node_handler.go
  pkg/application-grid-wrapper/storage/service_handler.go
  pkg/application-grid-wrapper/storage/storage.go
  pkg/application-grid-wrapper/storage/util.go
  pkg/edgeadm/common/update_config.go
  pkg/edgeadm/constant/manifests/application-grid-controller.go
  pkg/edgeadm/constant/manifests/application-grid-wrapper.go
Labels: kind/feature

#374 Support edge-to-edge, cloud-edge and edge-cloud service mutual access
  cmd/tunnel/app/options/options.go
  cmd/tunnel/app/server.go
  go.mod
  go.sum
  pkg/tunnel/conf/config.go
  pkg/tunnel/conf/config_test.go
  pkg/tunnel/context/conncontext.go
  pkg/tunnel/context/context.go
  pkg/tunnel/context/context_factory.go
  pkg/tunnel/context/node.go
  pkg/tunnel/context/nodecontext.go
  pkg/tunnel/proxy/common/connect.go
  pkg/tunnel/proxy/common/indexers/indexCache.go
  pkg/tunnel/proxy/common/proxy.go
  pkg/tunnel/proxy/handlers/common_handler.go
  pkg/tunnel/proxy/handlers/http-proxy_handler.go
  pkg/tunnel/proxy/modules/egress/connect/egress_server.go
  pkg/tunnel/proxy/modules/egress/egress.go
  pkg/tunnel/proxy/modules/http-proxy/connect/cloud_server.go
  pkg/tunnel/proxy/modules/http-proxy/connect/edge_server.go
  pkg/tunnel/proxy/modules/http-proxy/http_proxy.go
  pkg/tunnel/proxy/modules/ssh/connect/ssh_server.go
  pkg/tunnel/proxy/modules/ssh/ssh.go
  pkg/tunnel/util/const.go
  pkg/tunnel/util/util.go
Labels: kind/feature

#377 Remove the debug log of tunnel-edge
  pkg/tunnel/proxy/common/connect.go
Labels: kind/cleanup
